name: Amos

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - ready_for_review
      - closed

jobs:
  amos-ci:
    name: CI
    concurrency:
      group: amos-ci-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    uses: bentideswell/amos-ci/.github/workflows/amos-ci.yml@main
    permissions:
      contents: write
      issues: write
      pull-requests: write
